###
GET http://localhost:3000/api/productos HTTP/1.1


###
POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json


{
  "nombre": "Producto de prueba",
  "precio": 100,
  "descripcion": "Descripción del producto de prueba",
  "categoria": "Categoria de prueba"
}   

###
GET http://localhost:3000/api/productos/8 HTTP/1.1  

###
PUT http://localhost:3000/api/productos/8 HTTP/1.1
Content-Type: application/json


{
  "nombre": "Producto actualizado",
  "precio": 150,
  "descripcion": "Descripción actualizada del producto",
  "categoria": "Categoria actualizada"
}  


###
DELETE http://localhost:3000/api/productos/8 HTTP/1.1